Cleaned up all files
DelphiSoftware/Moodle_AppstreamLandingPage pull request #10
Opened 2021-02-24 20:40 UTC by JakeBroggy

Changes made:
- Removed several unnecessary lines of code from view.php
- Renamed landing.php to embed.php
- Deleted backup and test folders which were unnecessary
- Added some comments to provide clarity when navigating code
- Included scenario_config.js into view.php so that its contents can be kept separate from scenario_selection.js and landing_redirect.js

2021-02-24 21:18 UTC, rikerg-del requested changes

2021-02-24 21:18 UTC, rikerg-del commented on appstreamlanding/view.php
> +echo "<script src = '../mod/appstreamlanding/amd/src/scenario_config.js'></script>";
I see this is also being included via moodle's $PAGE settings. Is one of these redundant?

2021-02-24 21:18 UTC, rikerg-del commented on appstreamlanding/view.php
> +//Display the scenario selection page contents
Is it possible to include scenario_selection.php instead, since this code just replicates it? You would probably need to make it more page-neutral by stripping out everything but the variables and HTML, but then any changes being made don't have to be done twice.

2021-02-24 21:20 UTC, JakeBroggy commented on appstreamlanding/view.php
> +echo "<script src = '../mod/appstreamlanding/amd/src/scenario_config.js'></script>";
Oh that <script src> doesn't work so I had meant to remove it, but just ended up commenting it out. The one that works is via the moodle include, so we can remove the echo line entirely.

2021-02-25 14:32 UTC, walex-del commented on appstreamlanding/view.php
> +//Display the scenario selection page contents
The final version will do this.

2021-02-25 14:37 UTC, walex-del commented
While working on the code myself it looks like there was a bit of overlap done, but only because of the view.php page.
Other than that we're looking good. I was able to merge the two pieces of code from both Jake and Riker so that we're able to use the scenery_selection php and js, while still embedding.

I'm working on my own branch right now, but will rebase off of this one after.

2021-02-25 14:37 UTC, merged